---
version: '3.8'
services:
  as-rrd:
    platform: linux/x86_64
    image: yuril/aerospike-ha:0.0.2
    container_name: as-rrd
    depends_on:
      - aerospike
    links:
      - aerospike
    ports:
      - "8080:8080"
    environment:
      - AS_DB_DRIVER_HOST=aerospike
    command: [ "./start.sh" ]
  aerospike:
    image: aerospike:ee-7.1.0.1
    container_name: aerospike
    restart: always
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
...
